spring.application.name=Api-gateway

server.port=8087
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.server.webmvc.routes[0].id=User-Service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/userapp/**


spring.cloud.gateway.server.webmvc.routes[1].id=OrderService
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/order/v1/**